// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void aCT_TestData_ErrorOnDeviceType(IContext context, myfirstmodule.proxies.TestData _testData)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestData", _testData == null ? null : _testData.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_TestData_ErrorOnDeviceType").withParams(params).execute(context);
	}
	public static void aCT_TestData_Save(IContext context, myfirstmodule.proxies.TestData _testData)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestData", _testData == null ? null : _testData.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_TestData_Save").withParams(params).execute(context);
	}
	public static boolean sUB_TestData_Validate(IContext context, myfirstmodule.proxies.TestData _testData)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestData", _testData == null ? null : _testData.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.SUB_TestData_Validate").withParams(params).execute(context);
	}
}